@baseAddress = http://localhost:5001

###
POST {{baseAddress}}/api/v1/orders
Content-Type: application/json
Accept: application/json

{
  "DiscountRate": 10,
  "Address": {
    "Line": "123 Main St",
    "Province": "Ontario",
    "District": "Toronto",
    "ZipCode": "12345",
    "Street": "Main St"
  },
  "Payment": {
    "CardNumber": "4111111111111111",
    "CardHolderName": "John Doe",
    "Expiration": "12/25",
    "Cvc": "123",
    "Amount": 150.75
  },
  "Items": [
    {
      "ProductId": "3762ff3a-4b07-4918-b478-d58df7edbffe",
      "ProductName": "Course 20",
      "UnitPrice": 100
    },
    {
      "ProductId": "b1acc2a7-d4bc-4ea2-ae11-ac2800548e82",
      "ProductName": "Course 21",
      "UnitPrice": 200
    }
  ]
}
### Get All Orders by User ID
GET {{baseAddress}}/api/v1/orders
Accept: application/json
###
