FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/services/EduPlatform.Gateway/EduPlatform.Gateway.csproj", "src/services/EduPlatform.Gateway/"]
COPY ["src/shared/EduPlatform.Shared/EduPlatform.Shared.csproj", "src/shared/EduPlatform.Shared/"]
RUN dotnet restore "src/services/EduPlatform.Gateway/EduPlatform.Gateway.csproj"
COPY . .
WORKDIR "/src/src/services/EduPlatform.Gateway"
RUN dotnet build "./EduPlatform.Gateway.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./EduPlatform.Gateway.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EduPlatform.Gateway.dll"]
