
services:

  eduplatform.basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq
      - BusOption:Port=5672
      - IdentityOption:Address=http://keycloak:8080/realms/EduPlatformTenant
      - IdentityOption:Issuer=http://keycloak:8080/realms/EduPlatformTenant
      - ConnectionStrings:Redis=redis.db.basket:6379,password=Password12
    ports:
      - "8080"
    depends_on:
      - redis.db.basket
      - rabbitmq
    restart: always

  eduplatform.catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq
      - BusOption:Port=5672
      - IdentityOption:Address=http://keycloak:8080/realms/EduPlatformTenant
      - IdentityOption:Issuer=http://keycloak:8080/realms/EduPlatformTenant
      - MongoOption:ConnectionString=mongodb://myuser:Password12@mongo.db.catalog:27017
    ports:
      - "8080"
    depends_on:
      - mongo.db.catalog
      - rabbitmq
    restart: always


  eduplatform.discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq
      - BusOption:Port=5672
      - IdentityOption:Address=http://keycloak:8080/realms/EduPlatformTenant
      - IdentityOption:Issuer=http://keycloak:8080/realms/EduPlatformTenant
      - MongoOption:ConnectionString=mongodb://myuser:Password12@mongo.db.discount:27017
    ports:
      - "8080"
    depends_on:
      - mongo.db.discount
      - rabbitmq
    restart: always

  eduplatform.file.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq
      - BusOption:Port=5672
      - IdentityOption:Address=http://keycloak:8080/realms/EduPlatformTenant
      - IdentityOption:Issuer=http://keycloak:8080/realms/EduPlatformTenant
      - Storage__Root=/app/storage
    ports:
      - "8080"
    restart: always
    depends_on:
      - rabbitmq
      - file-storage-init
    volumes:
      - file_storage:/app/storage

  file-storage-init:
    image: alpine:3.20
    command: sh -c "mkdir -p /app/storage/files && chown -R 1654:1654 /app/storage && chmod -R 775 /app/storage"
    volumes:
      - file_storage:/app/storage


  eduplatform.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - IdentityOption:Address=http://keycloak:8080/realms/EduPlatformTenant
      - IdentityOption:Issuer=http://keycloak:8080/realms/EduPlatformTenant
    ports:
      - "8080"
    restart: always



  eduplatform.order.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq
      - BusOption:Port=5672
      - IdentityOption:Address=http://keycloak:8080/realms/EduPlatformTenant
      - IdentityOption:Issuer=http://keycloak:8080/realms/EduPlatformTenant
      - AddressUrlOption:PaymentUrl=http://eduplatform.payment.api:8080
      - ConnectionStrings:SqlServer=Server=sqlserver.db.order,1433;Database=OrderDb;User=Sa;Password=Password12*;Trusted_Connection=False;TrustServerCertificate=True;Integrated Security=False
    ports:
      - "8080"
    depends_on:
      - sqlserver.db.order
      - rabbitmq
      - keycloak
    restart: always
  eduplatform.payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq
      - BusOption:Port=5672
      - IdentityOption:Address=http://keycloak:8080/realms/EduPlatformTenant
      - IdentityOption:Issuer=http://keycloak:8080/realms/EduPlatformTenant
    ports:
      - "8080"
    restart: always
    depends_on:
      - rabbitmq

  eduplatform.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - MicroserviceOption:Catalog:BaseAddress=http://eduplatform.catalog.api:8080
      - MicroserviceOption:File:BaseAddress=http://eduplatform.file.api:8080
      - MicroserviceOption:Basket:BaseAddress=http://eduplatform.basket.api:8080
      - MicroserviceOption:Discount:BaseAddress=http://eduplatform.discount.api:8080
      - MicroserviceOption:Order:BaseAddress=http://eduplatform.order.api:8080
      - GatewayOption:BaseAddress=http://eduplatform.gateway:8080
      - IdentityOption:Address=http://keycloak:8080/realms/EduPlatformTenant
      - IdentityOption:BaseAddress=http://keycloak:8080
    ports:
      - "5050:8080"
    restart: always

volumes:
  file_storage: