@baseAddress = http://localhost:5083
@categoryId=08de457d-71a8-8a34-8eca-40e8eaa80000
GET {{baseAddress}}/api/categories
Accept: application/json

###
POST {{baseAddress}}/api/categories
Accept: application/json
Content-Type: application/json

{
  "name": "Go Eğitimleri"
}
###
GET {{baseAddress}}/api/categories/{{categoryId}}
Accept: application/json

###