@baseAddress = http://localhost:5228
@courseId=08de46bf-88f5-ecfc-8eca-40e8eaa80008
GET {{baseAddress}}/api/v1/baskets/user
Accept: application/json
###
POST {{baseAddress}}/api/v1/baskets/item
Accept: application/json
Content-Type: application/json

{
  "courseId":"{{courseId}}",
  "courseName": "yyyy6",
  "coursePrice": 200
}
###
DELETE {{baseAddress}}/api/v1/baskets/item/{{courseId}}
Accept: application/json
Content-Type: application/json
###
PUT {{baseAddress}}/api/v1/baskets/apply-discount-coupon
Accept: application/json
Content-Type: application/json

{
  "coupon":"abcdef",
  "discountRate":0.4
}
###
DELETE {{baseAddress}}/api/v1/baskets/remove-discount-coupon
Accept: application/json